### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Kharchova** [Kharchova/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by kharchovaCollaborator** [comment]
<h1 class="name"> Ryu Hoshi (リュウ Ryū) </h1>
<ul class="contacts">
<li>
<a href ="https://www.facebook.com/profile.php?id=100004808958030" rel="author" class="faceboook">
<span>   https://www.facebook.com/profile.php?id=100004808958030 </span>
</a>
</li>
<li>
<a href ="ryuwins@gmail.com" rel="author" class="mail">
<span> ryuwins@gmail.com </span>
</a>
</li>
<li>
<a href ="https://twitter.com/denjinryu" rel="author" class="twitter">
<span> https://twitter.com/denjinryu </span>
</a>
</li>
<li>
<a href ="https://www.instagram.com/sworn_ryu/ " rel="author" class="instagram">
<span> https://www.instagram.com/sworn_ryu/ </span>
</a>
</li>
</ul>
